apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pg-router
  labels:
    app.kubernetes.io/name: pg-router
    app.kubernetes.io/component: router
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pg-router
subjects:
  - kind: ServiceAccount
    name: pg-router
