/*
Copyright 2026 keiailab.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

package controller

import (
	"fmt"
	"strings"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"

	postgresv1alpha1 "github.com/keiailab/postgres-operator/api/v1alpha1"
	"github.com/keiailab/postgres-operator/internal/plugin"
)

// 본 파일은 PostgresCluster CR로부터 K8s 하위 자원(StatefulSet, Service,
// ConfigMap, Deployment)의 desired state를 생성하는 순수 함수들의 모음이다.
//
// 설계 원칙:
//   - 모든 함수는 입력에서 출력으로 결정적(stateless, side-effect 0).
//   - controllerutil.SetControllerReference 호출은 reconciler가 담당. 본 함수는
//     ObjectMeta까지만 채운다.
//   - 컨테이너 이미지 lookup은 internal/version/matrix.go의 결과만 사용한다.
//     본 파일에 imageRef:tag 하드코딩 금지.
//   - PostgreSQL 컨테이너 환경 변수, 볼륨 마운트, postgresql.conf의 세부
//     defaulting은 P1-M1 후속 작업에서 보강한다. 현재는 PG가 부팅 가능한 최소
//     스펙만 보장한다.

const (
	// pgContainerName은 PG 컨테이너의 식별자다. status 보고에서 동일 값을 참조.
	pgContainerName = "postgres"

	// pgPort는 PostgreSQL의 표준 포트다.
	pgPort int32 = 5432

	// pgDataMountPath는 PVC가 마운트되는 위치다.
	pgDataMountPath = "/var/lib/postgresql/data"

	// pgConfigMountPath는 ConfigMap이 마운트되는 위치다.
	pgConfigMountPath = "/etc/postgres-operator/conf"
)

// imageForVersion은 PostgresClusterSpec.Version 조합에 매칭되는 컨테이너 이미지
// 태그를 internal/version/matrix.go에서 가져온다. 매트릭스에 없으면 빈 문자열.
func imageForVersion(spec postgresv1alpha1.VersionSpec, gates map[string]bool) string {
	combo, ok := lookupCombo(spec, gates)
	if !ok {
		return ""
	}
	return combo.Image
}

// renderSharedPreloadLibraries는 등록된 모든 ExtensionPlugin을 우선순위 순으로
// 직렬화하여 shared_preload_libraries 값을 만든다.
//
// "Citus must be first" 규약은 Registry.Extensions()가 SharedPreloadOrder
// 오름차순으로 정렬해 반환하는 것으로 보장된다(ADR 0005, registry.go:Extensions).
// 본 함수는 그 결과를 콤마로 join 할 뿐이며, 별도 정렬 로직을 두지 않는다.
//
// 비어 있으면 빈 문자열 반환(예: 단위 테스트에서 Registry에 아무것도 등록 안 한
// 경우). 그 경우 ConfigMap에서 shared_preload_libraries 라인을 생략한다.
func renderSharedPreloadLibraries(reg *plugin.Registry) string {
	if reg == nil {
		return ""
	}
	exts := reg.Extensions()
	names := make([]string, 0, len(exts))
	for _, e := range exts {
		names = append(names, e.Name())
	}
	return strings.Join(names, ",")
}

// renderPostgresConf는 postgresql.conf의 본문을 생성한다.
// 현재는 최소집합. P10-T2/T3에서 extension별 옵션을 합성하도록 확장된다.
func renderPostgresConf(reg *plugin.Registry) string {
	var sb strings.Builder
	sb.WriteString("# Generated by keiailab-postgres-operator. Do not edit by hand.\n")
	sb.WriteString("listen_addresses = '*'\n")
	if spl := renderSharedPreloadLibraries(reg); spl != "" {
		fmt.Fprintf(&sb, "shared_preload_libraries = '%s'\n", spl)
	}
	return sb.String()
}

// buildConfigMap은 coordinator/worker/router 모두에서 동일 패턴으로 사용된다.
// 호출자가 name·role·pool을 정해 넘긴다.
func buildConfigMap(cluster *postgresv1alpha1.PostgresCluster, name, role, pool string, reg *plugin.Registry) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: cluster.Namespace,
			Labels:    SelectorLabels(cluster.Name, role, pool),
		},
		Data: map[string]string{
			"postgresql.conf": renderPostgresConf(reg),
		},
	}
}

// buildHeadlessService는 StatefulSet과 짝이 되는 ClusterIP=None Service를 만든다.
// 안정적 Pod DNS 제공이 목적이다.
func buildHeadlessService(cluster *postgresv1alpha1.PostgresCluster, name, role, pool string) *corev1.Service {
	labels := SelectorLabels(cluster.Name, role, pool)
	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: cluster.Namespace,
			Labels:    labels,
		},
		Spec: corev1.ServiceSpec{
			ClusterIP: corev1.ClusterIPNone,
			Selector:  labels,
			Ports: []corev1.ServicePort{{
				Name:       "postgres",
				Port:       pgPort,
				TargetPort: intstr.FromInt32(pgPort),
				Protocol:   corev1.ProtocolTCP,
			}},
		},
	}
}

// buildClientService는 라우터의 진입점 Service(ClusterIP)다.
func buildClientService(cluster *postgresv1alpha1.PostgresCluster, name, role string) *corev1.Service {
	labels := SelectorLabels(cluster.Name, role, "")
	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: cluster.Namespace,
			Labels:    labels,
		},
		Spec: corev1.ServiceSpec{
			Type:     corev1.ServiceTypeClusterIP,
			Selector: labels,
			Ports: []corev1.ServicePort{{
				Name:       "postgres",
				Port:       pgPort,
				TargetPort: intstr.FromInt32(pgPort),
				Protocol:   corev1.ProtocolTCP,
			}},
		},
	}
}

// buildPGStatefulSet은 coordinator 또는 worker pool의 StatefulSet desired state를
// 만든다. role="coordinator" 또는 "worker", pool은 worker일 때만 의미.
func buildPGStatefulSet(
	cluster *postgresv1alpha1.PostgresCluster,
	name, serviceName, role, pool, image, configMapName string,
	members int32,
	storage postgresv1alpha1.StorageSpec,
	resources corev1.ResourceRequirements,
) *appsv1.StatefulSet {
	labels := SelectorLabels(cluster.Name, role, pool)

	pvcAccessModes := storage.AccessModes
	if len(pvcAccessModes) == 0 {
		pvcAccessModes = []corev1.PersistentVolumeAccessMode{corev1.ReadWriteOnce}
	}

	pvcSpec := corev1.PersistentVolumeClaimSpec{
		AccessModes: pvcAccessModes,
		Resources: corev1.VolumeResourceRequirements{
			Requests: corev1.ResourceList{
				corev1.ResourceStorage: storage.Size,
			},
		},
		StorageClassName: storage.StorageClassName,
	}

	return &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: cluster.Namespace,
			Labels:    labels,
		},
		Spec: appsv1.StatefulSetSpec{
			ServiceName: serviceName,
			Replicas:    &members,
			Selector:    &metav1.LabelSelector{MatchLabels: labels},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: labels},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{{
						Name:      pgContainerName,
						Image:     image,
						Resources: resources,
						Ports: []corev1.ContainerPort{{
							Name:          "postgres",
							ContainerPort: pgPort,
							Protocol:      corev1.ProtocolTCP,
						}},
						VolumeMounts: []corev1.VolumeMount{
							{Name: "data", MountPath: pgDataMountPath},
							{Name: "config", MountPath: pgConfigMountPath, ReadOnly: true},
						},
					}},
					Volumes: []corev1.Volume{{
						Name: "config",
						VolumeSource: corev1.VolumeSource{
							ConfigMap: &corev1.ConfigMapVolumeSource{
								LocalObjectReference: corev1.LocalObjectReference{Name: configMapName},
							},
						},
					}},
				},
			},
			VolumeClaimTemplates: []corev1.PersistentVolumeClaim{{
				ObjectMeta: metav1.ObjectMeta{
					Name:   "data",
					Labels: labels,
				},
				Spec: pvcSpec,
			}},
		},
	}
}

// buildRouterDeployment는 stateless QueryRouter의 Deployment를 만든다.
// ADR 0003 §강제 메커니즘에 의해 PVC를 절대 마운트하지 않는다(StatefulSet 사용
// 금지). 본 함수는 P12-T2 시점에 cmd/router 바이너리 이미지로 교체된다. 현재는
// PG 베이스 이미지를 그대로 사용하는 placeholder.
func buildRouterDeployment(
	cluster *postgresv1alpha1.PostgresCluster,
	name, configMapName, image string,
	replicas int32,
	resources corev1.ResourceRequirements,
) *appsv1.Deployment {
	labels := SelectorLabels(cluster.Name, "router", "")

	return &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: cluster.Namespace,
			Labels:    labels,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{MatchLabels: labels},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: labels},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{{
						Name:      "router",
						Image:     image,
						Resources: resources,
						Ports: []corev1.ContainerPort{{
							Name:          "postgres",
							ContainerPort: pgPort,
							Protocol:      corev1.ProtocolTCP,
						}},
						VolumeMounts: []corev1.VolumeMount{
							{Name: "config", MountPath: pgConfigMountPath, ReadOnly: true},
						},
					}},
					Volumes: []corev1.Volume{{
						Name: "config",
						VolumeSource: corev1.VolumeSource{
							ConfigMap: &corev1.ConfigMapVolumeSource{
								LocalObjectReference: corev1.LocalObjectReference{Name: configMapName},
							},
						},
					}},
				},
			},
		},
	}
}

// hasResources는 ResourceRequirements가 비어 있는지 검사한다(테스트 보조).
//
//nolint:unused // Will be used in P1-M1 status reconcile defaults.
func hasResources(r corev1.ResourceRequirements) bool {
	if r.Requests == nil && r.Limits == nil {
		return false
	}
	return true
}

// quantityOrDefault는 nil 안전 헬퍼다.
//
//nolint:unused // Reserved for P1-M1 default sizing.
func quantityOrDefault(q *resource.Quantity, def string) resource.Quantity {
	if q == nil {
		return resource.MustParse(def)
	}
	return *q
}
