{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.postgresUser.enabled }}
{{- $postgresUserName := required "externalSecrets.postgresUser.name is required" .Values.externalSecrets.postgresUser.name -}}
{{- $postgresUserTargetName := required "externalSecrets.postgresUser.targetName is required" .Values.externalSecrets.postgresUser.targetName -}}
{{- $postgresUserUsernameRemoteKey := required "externalSecrets.postgresUser.usernameRemoteKey is required" .Values.externalSecrets.postgresUser.usernameRemoteKey -}}
{{- $postgresUserPasswordRemoteKey := required "externalSecrets.postgresUser.passwordRemoteKey is required" .Values.externalSecrets.postgresUser.passwordRemoteKey -}}
{{- $secretStoreName := required "externalSecrets.secretStoreName is required" .Values.externalSecrets.secretStoreName -}}
{{ include "keiailab.secrets.externalSecret" (dict
    "ctx" .
    "name" $postgresUserName
    "labels" (include "postgres-operator.labels" .)
    "refreshInterval" .Values.externalSecrets.refreshInterval
    "secretStoreKind" .Values.externalSecrets.secretStoreKind
    "secretStoreName" $secretStoreName
    "targetName" $postgresUserTargetName
    "data" (list
      (dict "secretKey" .Values.externalSecrets.postgresUser.usernameKey "remoteKey" $postgresUserUsernameRemoteKey)
      (dict "secretKey" .Values.externalSecrets.postgresUser.passwordKey "remoteKey" $postgresUserPasswordRemoteKey))) }}
{{- end }}
{{ if and .Values.externalSecrets.enabled .Values.externalSecrets.poolerAuth.enabled }}
{{- $poolerAuthName := required "externalSecrets.poolerAuth.name is required" .Values.externalSecrets.poolerAuth.name -}}
{{- $poolerAuthTargetName := required "externalSecrets.poolerAuth.targetName is required" .Values.externalSecrets.poolerAuth.targetName -}}
{{- $poolerAuthUserlistRemoteKey := required "externalSecrets.poolerAuth.userlistRemoteKey is required" .Values.externalSecrets.poolerAuth.userlistRemoteKey -}}
{{- $secretStoreName := required "externalSecrets.secretStoreName is required" .Values.externalSecrets.secretStoreName -}}
---
{{ include "keiailab.secrets.externalSecret" (dict
    "ctx" .
    "name" $poolerAuthName
    "labels" (include "postgres-operator.labels" .)
    "refreshInterval" .Values.externalSecrets.refreshInterval
    "secretStoreKind" .Values.externalSecrets.secretStoreKind
    "secretStoreName" $secretStoreName
    "targetName" $poolerAuthTargetName
    "data" (list
      (dict "secretKey" .Values.externalSecrets.poolerAuth.userlistKey "remoteKey" $poolerAuthUserlistRemoteKey))) }}
{{- end }}
{{ if and .Values.externalSecrets.enabled .Values.externalSecrets.replicaSourcePassword.enabled }}
{{- $replicaSourcePasswordName := required "externalSecrets.replicaSourcePassword.name is required" .Values.externalSecrets.replicaSourcePassword.name -}}
{{- $replicaSourcePasswordTargetName := required "externalSecrets.replicaSourcePassword.targetName is required" .Values.externalSecrets.replicaSourcePassword.targetName -}}
{{- $replicaSourcePasswordPasswordRemoteKey := required "externalSecrets.replicaSourcePassword.passwordRemoteKey is required" .Values.externalSecrets.replicaSourcePassword.passwordRemoteKey -}}
{{- $secretStoreName := required "externalSecrets.secretStoreName is required" .Values.externalSecrets.secretStoreName -}}
---
{{ include "keiailab.secrets.externalSecret" (dict
    "ctx" .
    "name" $replicaSourcePasswordName
    "labels" (include "postgres-operator.labels" .)
    "refreshInterval" .Values.externalSecrets.refreshInterval
    "secretStoreKind" .Values.externalSecrets.secretStoreKind
    "secretStoreName" $secretStoreName
    "targetName" $replicaSourcePasswordTargetName
    "data" (list
      (dict "secretKey" .Values.externalSecrets.replicaSourcePassword.passwordKey "remoteKey" $replicaSourcePasswordPasswordRemoteKey))) }}
{{- end }}
